name: calculadora_imc
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  mockito: ^5.3.0
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.2.0
  lints: ^4.0.0
  test: ^1.24.0
